services:
  database:
    container_name: postgres-myproject
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: abdelrahman
      POSTGRES_PASSWORD: abdelrahman123
      POSTGRES_DB: djangoapp
    ports:
      - '5442:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin-myproject
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default login email
      PGADMIN_DEFAULT_PASSWORD: admin         # Default login password
    ports:
      - '5050:80'  # Expose pgAdmin on localhost:5050

volumes:
  postgres_data:  # Persistent storage for PostgreSQL data