# Generated by Django 5.2 on 2025-04-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('crimeTime', models.TextField(blank=True, null=True)),
                ('crimeType', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_pic', models.URLField(blank=True, null=True)),
                ('likes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myproject.post')),
            ],
        ),
    ]
