# Generated by Django 5.1.7 on 2025-03-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_user_alter_createdby_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
