# Generated by Django 5.2 on 2025-04-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_rename_id_comment_comment_id_rename_id_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
