# Generated by Django 5.2 on 2025-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crimeTime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='crimeType',
            field=models.TextField(blank=True, null=True),
        ),
    ]
